language: go
sudo: required

go:
  - 1.13.x

go_import_path: github.com/containerd/project

install:
  - go get -u github.com/vbatts/git-validation
  - go get -u github.com/kunalkushwaha/ltag

script:
  - DCO_VERBOSITY=-q script/validate/dco
  - script/validate/fileheader
